import { Player } from "./player.interface";

export interface Team {
  atletas: Player[];
  time: {
    nome: string;
    nome_cartola: string;
    time_id: number;
    temporada_inicial?: number;
    cor_fundo_escudo?: string;
    cor_camisa?: string;
    cor_borda_escudo?: string;
    foto_perfil?: string;
    globo_id?: string;
    url_escudo_svg?: string;
    url_escudo_png?: string;
    url_camisa_svg?: string;
    url_camisa_png?: string;
    slug?: string;
    cor_secundaria_estampa_escudo?: string;
    sorteio_pro_num?: number | null;
    cor_primaria_estampa_camisa?: string;
    cor_secundaria_estampa_camisa?: string;
    cor_primaria_estampa_escudo?: string;
    rodada_time_id?: number;
    facebook_id?: number | null;
    tipo_escudo?: number;
    tipo_adorno?: number;
    esquema_id?: number;
    tipo_estampa_camisa?: number;
    tipo_estampa_escudo?: number;
    patrocinador1_id?: number;
    clube_id?: number;
    tipo_camisa?: number;
    patrocinador2_id?: number;
    assinante?: boolean;
    simplificado?: boolean;
    cadastro_completo?: boolean;
    lgpd_removido?: boolean;
    lgpd_quarentena?: boolean;
  };
  capitao_id: number;
  pontos: number;
  pontos_campeonato: number;
  pontos_formatado?: string;
  pontos_campeonato_formatado?: string;
  patrimonio: number;
  parcial?: number;
  parcial_formatado?: string;
  reservas?: any;
  esquema_id?: any;
  rodada_atual?: any;
  valor_time?: any;
  ranking?: any;
}
